FROM fedora:44

ARG USERNAME=dev
ARG UID=1000
ARG GID=1000
ARG HOMEDIR=/home/dev

RUN dnf -y install \
        gcc gcc-c++ clang clang-tools-extra lld lldb \
        make cmake ninja-build \
        autoconf automake libtool pkgconf-pkg-config \
        git curl wget openssh-clients \
        vim-enhanced nano less file which findutils diffutils patch \
        tar gzip xz bzip2 unzip zip \
        ca-certificates \
        python3 python3-pip python3-virtualenv python3-devel \
        nodejs npm \
        rust cargo rustfmt clippy \
        bash-completion man-db \
        sudo procps-ng iputils \
    && dnf clean all \
    && rm -rf /var/cache/dnf

ARG LANGPACK=en
RUN dnf -y install glibc-langpack-${LANGPACK} \
    && dnf clean all && rm -rf /var/cache/dnf

RUN dnf -y install \
        qt6-qtbase qt6-qtbase-devel \
        qt6-qtdeclarative qt6-qtdeclarative-devel \
        qt6-qttools qt6-qttools-devel \
        qt6-qtsvg qt6-qtsvg-devel \
        qt6-rpm-macros \
        alsa-lib-devel qt6-qtmultimedia-devel \
    && dnf clean all && rm -rf /var/cache/dnf

RUN groupadd -g ${GID} ${USERNAME} \
 && useradd -u ${UID} -g ${GID} -d ${HOMEDIR} -M -s /bin/bash ${USERNAME} \
 && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
 && chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}
WORKDIR ${HOMEDIR}
CMD ["sleep", "infinity"]
